/* tslint:disable */
/* eslint-disable */
/**
 * しずかなインターネット API
 * - このAPIは自分の記事データを取得するために利用します。他のユーザーのデータを取得することはできません。 - APIは[プロジェクトのスポンサー](https://sizu.me/sponsors/purchase)のみが利用できます。 - 認証やレート制限などについては[GitHubリポジトリ](https://github.com/catnose99/quiet-internet-api-docs)を参照してください。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';
import type { PostMeta } from './PostMeta';
import {
    PostMetaFromJSON,
    PostMetaFromJSONTyped,
    PostMetaToJSON,
} from './PostMeta';

/**
 * 
 * @export
 * @interface ApiV1PostsGet200Response
 */
export interface ApiV1PostsGet200Response {
    /**
     * 
     * @type {Array<PostMeta>}
     * @memberof ApiV1PostsGet200Response
     */
    posts?: Array<PostMeta>;
    /**
     * 
     * @type {Pagination}
     * @memberof ApiV1PostsGet200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ApiV1PostsGet200Response interface.
 */
export function instanceOfApiV1PostsGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1PostsGet200ResponseFromJSON(json: any): ApiV1PostsGet200Response {
    return ApiV1PostsGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1PostsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1PostsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'posts': !exists(json, 'posts') ? undefined : ((json['posts'] as Array<any>).map(PostMetaFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ApiV1PostsGet200ResponseToJSON(value?: ApiV1PostsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'posts': value.posts === undefined ? undefined : ((value.posts as Array<any>).map(PostMetaToJSON)),
        'pagination': PaginationToJSON(value.pagination),
    };
}

