/* tslint:disable */
/* eslint-disable */
/**
 * しずかなインターネット API
 * - このAPIは自分の記事データを取得するために利用します。他のユーザーのデータを取得することはできません。 - APIは[プロジェクトのスポンサー](https://sizu.me/sponsors/purchase)のみが利用できます。 - 認証やレート制限などについては[GitHubリポジトリ](https://github.com/catnose99/quiet-internet-api-docs)を参照してください。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostDetail } from './PostDetail';
import {
    PostDetailFromJSON,
    PostDetailFromJSONTyped,
    PostDetailToJSON,
} from './PostDetail';

/**
 * 
 * @export
 * @interface ApiV1PostsSlugGet200Response
 */
export interface ApiV1PostsSlugGet200Response {
    /**
     * 
     * @type {PostDetail}
     * @memberof ApiV1PostsSlugGet200Response
     */
    post?: PostDetail;
}

/**
 * Check if a given object implements the ApiV1PostsSlugGet200Response interface.
 */
export function instanceOfApiV1PostsSlugGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1PostsSlugGet200ResponseFromJSON(json: any): ApiV1PostsSlugGet200Response {
    return ApiV1PostsSlugGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1PostsSlugGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1PostsSlugGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'post': !exists(json, 'post') ? undefined : PostDetailFromJSON(json['post']),
    };
}

export function ApiV1PostsSlugGet200ResponseToJSON(value?: ApiV1PostsSlugGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'post': PostDetailToJSON(value.post),
    };
}

