/* tslint:disable */
/* eslint-disable */
/**
 * しずかなインターネット API
 * - このAPIは自分の記事データを取得するために利用します。他のユーザーのデータを取得することはできません。 - APIは[プロジェクトのスポンサー](https://sizu.me/sponsors/purchase)のみが利用できます。 - 認証やレート制限などについては[GitHubリポジトリ](https://github.com/catnose99/quiet-internet-api-docs)を参照してください。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostDetail
 */
export interface PostDetail {
    /**
     * 
     * @type {any}
     * @memberof PostDetail
     */
    slug?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PostDetail
     */
    title?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PostDetail
     */
    bodyCharacterCount?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PostDetail
     */
    visibility?: PostDetailVisibilityEnum;
    /**
     * 
     * @type {any}
     * @memberof PostDetail
     */
    tags?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PostDetail
     */
    createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PostDetail
     */
    updatedAt?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PostDetail
     */
    bodyMarkdown?: string;
    /**
     * 
     * @type {string}
     * @memberof PostDetail
     */
    bodyHtml?: string;
}


/**
 * @export
 */
export const PostDetailVisibilityEnum = {
    Myself: 'MYSELF',
    Anyone: 'ANYONE'
} as const;
export type PostDetailVisibilityEnum = typeof PostDetailVisibilityEnum[keyof typeof PostDetailVisibilityEnum];


/**
 * Check if a given object implements the PostDetail interface.
 */
export function instanceOfPostDetail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostDetailFromJSON(json: any): PostDetail {
    return PostDetailFromJSONTyped(json, false);
}

export function PostDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'bodyCharacterCount': !exists(json, 'bodyCharacterCount') ? undefined : json['bodyCharacterCount'],
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'bodyMarkdown': !exists(json, 'bodyMarkdown') ? undefined : json['bodyMarkdown'],
        'bodyHtml': !exists(json, 'bodyHtml') ? undefined : json['bodyHtml'],
    };
}

export function PostDetailToJSON(value?: PostDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'title': value.title,
        'bodyCharacterCount': value.bodyCharacterCount,
        'visibility': value.visibility,
        'tags': value.tags,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'bodyMarkdown': value.bodyMarkdown,
        'bodyHtml': value.bodyHtml,
    };
}

