name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: No operation
        run: echo "No operation"
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: quiet-internet-api
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
